# Generated by Django 4.0.4 on 2022-06-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_enrollment_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('ects', models.IntegerField()),
                ('sem_red', models.IntegerField()),
                ('sem_izv', models.IntegerField()),
                ('izborni', models.CharField(choices=[('DA', 'da'), ('NE', 'ne')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.predmeti'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
