# Generated by Django 4.0.4 on 2022-06-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_predmeti_alter_enrollment_subject_delete_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmeti',
            old_name='code',
            new_name='kod',
        ),
    ]
