# Generated by Django 4.0.4 on 2022-06-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_role_status_predmeti_nositelj_alter_myuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning.subjectstatus'),
        ),
    ]
