# Generated by Django 4.0.4 on 2022-06-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elearning.program'),
        ),
    ]
