# Generated by Django 4.0.4 on 2022-06-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_alter_predmeti_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izborni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='predmeti',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.program'),
        ),
        migrations.AlterField(
            model_name='predmeti',
            name='izborni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.izborni'),
        ),
    ]
